### PR TITLE
Avoid using Function constructor.

### PR DESCRIPTION
**Pull request by vrana**
Using the Function constructor is not compatible with CSP without
'unsafe-eval' as it evals the passed code. Use a function literal
instead.

### CODE REVIEW

**Comment by mbostock** [comment]
This behavior is noted in the README along with the suggestion to use parseRows if a CSP is in place. Changing the implementation as proposed here had a substantial negative performance impact, at least last time I measured it, and so I am wary of changing the default behavior. If you want to verify that this behavior has been fixed in modern browsers for large input files, then I will reconsider this request. Th

**Comment by vrana** [comment]
Please give me instructions about how you want to measure this.

**Comment by vrana** [comment]
I was able to reproduce the slowness in Chrome by parsing `Appearances.csv` from http://seanlahman.com/baseball-archive/statistics/. I'll debug what's going on and update this pull request with a faster version.

Browser | Old code | New Code
--- | --- | ---
Chrome 58 | 376 ms | 1462 ms

**Comment by vrana** [comment]
I was able to bring it down with this code:

```js
function objectConverter(columns) {
  var result = {};
  return function(d) {
    for (var i = 0; i < columns.length; i++) {
      result[columns[i]] = d[i];
    }
    return result;
  };
}
```

Browser | Old code | New Code
--- | --- | ---
Chrome 58 Linux | 376 ms | 539 ms
Firefox 53 Linux | 941 ms | 725 ms

It's slightly faster in Firefox and slightly slower in Chrome. Is this acceptable for you?

I've also updated the README which should appear if you re-open this pull request.

**Comment by mbostock** [comment]
That implementation returns the same object for every row rather than a new object for each row.

**Comment by vrana** [comment]
You are right.

**Comment by vrana** [comment]
I will not be able to make this fast. Thanks for your feedback.

**Comment by vrana** [comment]
Created #87.

**Pull request closed without merging**
