### PR TITLE
dsv2json: Add '-a/--autotype' flag to use d3.autoType

### PR DESCRIPTION
**Pull request by joallard**
It was a need I had converting some files, seemed straightforward enough.

I'm thinking we don't want to make this the default for now.

### CODE REVIEW

**Comment by Fil** [comment]
> I'm thinking we don't want to make this the default for now.

Agree: the default should be the same in the cli utility and in d3.

**Comment by Fil** [comment]
Sorry for _l'esprit d'escalier_ but shouldn't we use camel case (`autoType`), like the original method?

**Comment by mbostock** [comment]
Probably —auto-type…

**Comment by joallard** [comment]
I've pondered this myself, and my thought process was that I'd be pretty disappointed to type `--autotype` only for it to get ignored because I didn't write `--auto-type`. That said, that is pretty minor, considering people will either use `-a` or consult the help. It does make complete sense to keep it consistent with the method name. I don't have strong opinions on this.

Let me know if you'd like me to fixup the commit with `--auto-type`

**Comment by Fil** [comment]
merged with syntax `--auto-type`; thank you!

**Comment by joallard** [comment]
Sounds good, merci @Fil!

**Pull request merged**
